# inpiration: 
# https://github.com/microsoft/pyright/issues/2518
# https://github.com/python/typeshed/blob/master/.github/workflows/tests.yml

name: Check stubs

on:
  workflow_dispatch:
  # push:
  # pull_request:

permissions:
  contents: read

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  pyright:
    name: Run pyright against the stubs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-platform: ["Linux"] # , "Windows", "Darwin"]
        #python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: [ "3.9"]
      fail-fast: false
    env:
      PYRIGHT_VERSION: 1.1.204 # Must match pyright_test.py.
    steps:
      - uses: actions/checkout@v2

      # - uses: jakebailey/pyright-action@v1
      #   with:
      #     version: ${{ env.PYRIGHT_VERSION }}
      #     python-platform: ${{ matrix.python-platform }}
      #     python-version: ${{ matrix.python-version }}
      #     no-comments: ${{ matrix.python-version != '3.9' || matrix.python-platform != 'Linux' }}  # Having each job create the same comment is too noisy.
      #     project: ./pyrightconfig.stricter.json
      
      - uses: jakebailey/pyright-action@v1
        with:
          version: ${{ env.PYRIGHT_VERSION }}
          python-platform: ${{ matrix.python-platform }}
          python-version: ${{ matrix.python-version }}
          no-comments: ${{ matrix.python-version != '3.9' || matrix.python-platform != 'Linux' }}  # Having each job create the same comment is too noisy.